package:
  name: lmfit-c
  version: "8.2.2.post30"

source:
  git_url: https://github.com/NSLS-II/lmfit
  git_rev: 6b85290e61955feed3a152bed0e765a847c24ac6

build:
  number: 11

requirements:
  build:
    - cmake
    - {{ compiler('c') }}

about:
  home: https://github.com/NSLS-II/lmfit
  license: FreeBSD 
